/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Exercise = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'repsOrDuration' : IDL.Text,
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'steps' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'safetyTips' : IDL.Vec(IDL.Text),
  'bodyPart' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getExerciseById' : IDL.Func([IDL.Nat], [Exercise], ['query']),
  'getExercisesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Exercise)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Exercise = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'repsOrDuration' : IDL.Text,
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'steps' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'safetyTips' : IDL.Vec(IDL.Text),
    'bodyPart' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getExerciseById' : IDL.Func([IDL.Nat], [Exercise], ['query']),
    'getExercisesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Exercise)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };